const globalConfig = {
	workspaces: {
		'.': {
			ignoreBinaries: ['check-outdated'],
			ignoreDependencies: ['wrangler']
		},
		'packages/*': {
			paths: {
				'$app/*': ['../../node_modules/@sveltejs/kit/src/runtime/app/*']
			},
			ignoreUnresolved: ['\\$dist/.*', '\\$lib/paraglide/.*', '\\$env/*', '\\$types'],
			ignoreDependencies: ['tailwindcss', 'flowbite', 'autoprefixer']
		}
	}
};

export default {
	eslint: {
		config: []
	},
	workspaces: {
		...globalConfig.workspaces,
		'packages/dropin-service': {
			...globalConfig.workspaces['packages/*'],
			ignore: [
				'./src/lib-v4/sdk/*',
				'./src/lib-v4/browser/telemetry.js', // Used by sdk/index.js which is bundled separately with esbuild
				'./src/lib/services/*', // Temporary when migrating to v5
				'./src/paraglide/**', // Auto-generated by Paraglide
        '**/eslint.config.js',
				'./src/hooks.js' // Used by SvelteKit SDK, no export directly usage.
			],
			ignoreExports: ['worker', 'setConfiguratorForHandlers']
		},
		'packages/dash': {
			...globalConfig.workspaces['packages/*'],
			paths: {
				...globalConfig.workspaces['packages/*'].paths,
				'$lib/*': ['./src/lib/*']
			},
			ignoreDependencies: [
				...globalConfig.workspaces['packages/*'].ignoreDependencies,
				'@firmly/eslint-config',
				'@storybook/addon-themes'
			],
			ignoreUnresolved: [
				...globalConfig.workspaces['packages/*'].ignoreUnresolved,
				'\\$lib/.*', // SvelteKit $lib alias
				'\\./types',
				'svelte',
				'svelte/store',
				'svelte/transition',
				'svelte/animate',
				'svelte/easing',
				'@storybook/addon-essentials',
				'@storybook/addon-interactions',
				'@storybook/addon-postcss'
			],
			ignore: [
				'**/*.stories.svelte', // Story files
				'./src/lib/components/ui/**', // shadcn components
				'./*.config.js',
				'./*.config.cjs',
				'**/__mocks__/**'
			]
		},
		'packages/var-service': {
			...globalConfig.workspaces['packages/*'],
			paths: {
				...globalConfig.workspaces['packages/*'].paths,
				'$lib/*': ['./src/lib/*']
			},
			ignoreDependencies: ['@storybook/test'],
			ignore: ['./$types', '*.config.js']
		},
		'packages/session-recorder': {
			ignoreDependencies: ['jsdom']
		},
		'packages/eslint-config': {
			// Used as plugin by prettier, tailwind
			ignoreDependencies: ['prettier-plugin-svelte', 'prettier-plugin-tailwindcss']
		},
		'packages/dash-do': {
			ignore: ['./eslint.config.js'],
			// ESLint dependencies used by eslint.config.js
			// cloudflare:test is a Cloudflare Workers test module, not an npm package
			ignoreDependencies: [
				'@babel/eslint-parser',
				'@babel/plugin-syntax-import-assertions',
				'eslint-plugin-import',
				'cloudflare'
			]
		}
	}
};
